#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-tsne
Version  : 0.1.3
Release  : 8
URL      : https://cran.r-project.org/src/contrib/tsne_0.1-3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/tsne_0.1-3.tar.gz
Summary  : T-Distributed Stochastic Neighbor Embedding for R (t-SNE)
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : clr-R-helpers

%description
No detailed description available

%prep
%setup -q -c -n tsne

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1521269113

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1521269113
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library tsne
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library tsne
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library tsne
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library tsne|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/tsne/DESCRIPTION
/usr/lib64/R/library/tsne/INDEX
/usr/lib64/R/library/tsne/Meta/Rd.rds
/usr/lib64/R/library/tsne/Meta/features.rds
/usr/lib64/R/library/tsne/Meta/hsearch.rds
/usr/lib64/R/library/tsne/Meta/links.rds
/usr/lib64/R/library/tsne/Meta/nsInfo.rds
/usr/lib64/R/library/tsne/Meta/package.rds
/usr/lib64/R/library/tsne/NAMESPACE
/usr/lib64/R/library/tsne/NEWS
/usr/lib64/R/library/tsne/R/tsne
/usr/lib64/R/library/tsne/R/tsne.rdb
/usr/lib64/R/library/tsne/R/tsne.rdx
/usr/lib64/R/library/tsne/help/AnIndex
/usr/lib64/R/library/tsne/help/aliases.rds
/usr/lib64/R/library/tsne/help/paths.rds
/usr/lib64/R/library/tsne/help/tsne.rdb
/usr/lib64/R/library/tsne/help/tsne.rdx
/usr/lib64/R/library/tsne/html/00Index.html
/usr/lib64/R/library/tsne/html/R.css
